# Generated by Django 5.0.2 on 2024-02-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project1Title', models.CharField(default='Project 1 Title', max_length=100)),
                ('p1FinalCap', models.CharField(default='final product caption', max_length=50)),
                ('p1ProgressCap1', models.CharField(default='progress image 1 caption', max_length=50)),
                ('p1ProgressCap2', models.CharField(default='progress image 2 caption', max_length=50)),
                ('p1ProgressCap3', models.CharField(default='progress image 3 caption', max_length=50)),
                ('p1Explanation', models.CharField(default='short explanation of your design process', max_length=300)),
                ('project2Title', models.CharField(default='Project 2 Title', max_length=100)),
                ('p2FinalCap', models.CharField(default='final product caption', max_length=50)),
                ('p2ProgressCap1', models.CharField(default='progress image 1 caption', max_length=50)),
                ('p2ProgressCap2', models.CharField(default='progress image 2 caption', max_length=50)),
                ('p2ProgressCap3', models.CharField(default='progress image 3 caption', max_length=50)),
                ('p2Explanation', models.CharField(default='short explanation of your design process', max_length=300)),
                ('project3Title', models.CharField(default='Project 3 Title', max_length=100)),
                ('p3FinalCap', models.CharField(default='final product caption', max_length=50)),
                ('p3ProgressCap1', models.CharField(default='progress image 1 caption', max_length=50)),
                ('p3ProgressCap2', models.CharField(default='progress image 2 caption', max_length=50)),
                ('p3ProgressCap3', models.CharField(default='progress image 3 caption', max_length=50)),
                ('p3Explanation', models.CharField(default='short explanation of your design process', max_length=300)),
                ('project4Title', models.CharField(default='Project 4 Title', max_length=100)),
                ('p4FinalCap', models.CharField(default='final product caption', max_length=50)),
                ('p4ProgressCap1', models.CharField(default='progress image 1 caption', max_length=50)),
                ('p4ProgressCap2', models.CharField(default='progress image 2 caption', max_length=50)),
                ('p4ProgressCap3', models.CharField(default='progress image 3 caption', max_length=50)),
                ('p4Explanation', models.CharField(default='short explanation of your design process', max_length=300)),
            ],
        ),
    ]
