# Generated by Django 5.0.2 on 2024-02-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='p1FinalImg',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p1ProgressImg1',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p1ProgressImg2',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p1ProgressImg3',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p2FinalImg',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p2ProgressImg1',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p2ProgressImg2',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p2ProgressImg3',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p3FinalImg',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p3ProgressImg1',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p3ProgressImg2',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p3ProgressImg3',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p4FinalImg',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p4ProgressImg1',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p4ProgressImg2',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='template',
            name='p4ProgressImg3',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
    ]
