# Generated by Django 4.2.7 on 2024-03-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artfolio', '0002_template_p1finalimg_template_p1progressimg1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterTag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='filterTag',
            field=models.ManyToManyField(to='Artfolio.filter'),
        ),
    ]
