# Generated by Django 4.2.7 on 2024-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artfolio', '0003_filter_template_filtertag'),
    ]

    operations = [
        migrations.CreateModel(
            name='filterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='template',
            name='filterTag',
        ),
        migrations.AlterField(
            model_name='template',
            name='p1FinalImg',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p1ProgressImg1',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p1ProgressImg2',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p1ProgressImg3',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p2FinalImg',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p2ProgressImg1',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p2ProgressImg2',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p2ProgressImg3',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p3FinalImg',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p3ProgressImg1',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p3ProgressImg2',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p3ProgressImg3',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p4FinalImg',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p4ProgressImg1',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p4ProgressImg2',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='p4ProgressImg3',
            field=models.ImageField(upload_to='projectImages'),
        ),
        migrations.DeleteModel(
            name='filter',
        ),
    ]
