# Generated by Django 4.2.7 on 2024-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artfolio', '0004_filtertag_remove_template_filtertag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='filterTag',
            field=models.ManyToManyField(to='Artfolio.filtertag'),
        ),
    ]
