# Generated by Django 4.2.7 on 2024-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artfolio', '0005_template_filtertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='filterTag',
            field=models.ManyToManyField(blank=True, related_name='template', to='Artfolio.filtertag'),
        ),
    ]
