# Generated by Django 4.2.7 on 2024-03-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artfolio', '0006_alter_template_filtertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtertag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
