# Generated by Django 4.2.7 on 2024-03-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artfolio', '0007_alter_filtertag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='filterTag',
            field=models.ManyToManyField(blank=True, related_name='templates', to='Artfolio.filtertag'),
        ),
    ]
