# Generated by Django 4.2.7 on 2024-03-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artfolio', '0008_alter_template_filtertag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='filterTag',
            new_name='filterTags',
        ),
    ]
